# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./CV.html
          outputFile: ./CV-Andrew-Byrne.pdf
          pdfOptions: '{"format": "A4"}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CV PDF
          path: ./CV-Andrew-Byrne.pdf

      - name: Send mail
          uses: dawidd6/action-send-mail@v3
          with:
            # Specify connection via URL (replaces server_address, server_port, secure,
            # username and password)
            #
            # Format:
            #
            #  * smtp://user:password@server:port
            #  * smtp+starttls://user:password@server:port
            # Required mail server address if not connection_url:
            server_address: smtp.gmail.com
            subject: CV
            # Required recipients' addresses:
            to: abyrne85@gmail.com
            # Required sender full name (address can be skipped):
            from: Andrew Byrne # <user@example.com>
            # Optional HTML body read from file:
            html_body: file://CV.html
            # Optional attachments:
            attachments: ./CV-Andrew-Byrne.pdf
            # Optional priority: 'high', 'normal' (default) or 'low'
            priority: low