# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./CV.html
          outputFile: ./CV-Andrew-Byrne.pdf
          pdfOptions: '{"format": "A4", "pageRanges": "1"}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CV PDF
          path: ./CV-Andrew-Byrne.pdf
